// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADPgYp1QDLB79Mj6smnhVfuQi1I_FtaZI',
    appId: '1:842770194583:web:11734ba7072c49d926c9d2',
    messagingSenderId: '842770194583',
    projectId: 'expenditure-app-857c6',
    authDomain: 'expenditure-app-857c6.firebaseapp.com',
    storageBucket: 'expenditure-app-857c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGA-GTnA7A3WK9hq1hqSV9VZ_2NobzTG4',
    appId: '1:842770194583:android:0890204662421f5d26c9d2',
    messagingSenderId: '842770194583',
    projectId: 'expenditure-app-857c6',
    storageBucket: 'expenditure-app-857c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS05TJjFCXwkIZ9vbzGyhDI4o00MZWLhY',
    appId: '1:842770194583:ios:a1cd0d0b525e1d7a26c9d2',
    messagingSenderId: '842770194583',
    projectId: 'expenditure-app-857c6',
    storageBucket: 'expenditure-app-857c6.appspot.com',
    iosBundleId: 'com.example.expenseManagementApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS05TJjFCXwkIZ9vbzGyhDI4o00MZWLhY',
    appId: '1:842770194583:ios:a1cd0d0b525e1d7a26c9d2',
    messagingSenderId: '842770194583',
    projectId: 'expenditure-app-857c6',
    storageBucket: 'expenditure-app-857c6.appspot.com',
    iosBundleId: 'com.example.expenseManagementApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADPgYp1QDLB79Mj6smnhVfuQi1I_FtaZI',
    appId: '1:842770194583:web:c0f0b1e35f412dfe26c9d2',
    messagingSenderId: '842770194583',
    projectId: 'expenditure-app-857c6',
    authDomain: 'expenditure-app-857c6.firebaseapp.com',
    storageBucket: 'expenditure-app-857c6.appspot.com',
  );
}
